### PR TITLE
Handle sensor observing own part

### PR DESCRIPTION
**Pull request by jsolson**
Change SmartSensorModuleBase class to gracefully handle lights not present on the part.
Update SmartSRB to permit being a module of the SRB part, rather than surface attached.
Part researched check added.

Draft. Works in Sandbox.

### CODE REVIEW

**Comment by jsolson** [comment]
I'm debating the merits of two separate classes vs one do all class. I'd hate to see too much code duplication because maintenance is a headache, but then trying to work two modes into one partmodule can be hard-to-find-bug prone.

**Comment by linuxgurugamer** [comment]
Then don't.  I already have it as a seperate part module for the embedded version.

**Comment by linuxgurugamer** [comment]
I was about to release it when I saw your PR

**Comment by jsolson** [comment]
Go ahead. This was just a quick and dirty hack to see how tricky it would be to get it working.

**Comment by jsolson** [comment]
And, if you're planning on including a patch to put this on every srb, I'd suggest isArmed = false in the cfg.

**Comment by linuxgurugamer** [comment]
It's an optional patch, will be enabled via the PatchManager
When will the sensor code be finished, if soon, I could wait for it.
I've pushed the change to Github if you want to pull it down.  I won't be releasing it for a few days

**Comment by jsolson** [comment]
Ok I like the separate class better. It's a much easier read. Maybe make an SmartSRBBase class to put the shared code in, then decend both variants from that?

What's going on here? ([link](https://github.com/linuxgurugamer/KerbalSmartParts/blob/4dcd9e6a68ed4724fe1a006e9f19e463bf092840/SmartParts/EmbeddedSmartSRB.cs#L117)) When the engine activates, arm the module? How does the user avoid the module triggering if it's embedded everywhere? I'm using isArmed as the user toggle for turning detection on/off, and isEnabled to disable the entire module UI and all if it's not researched.

**Comment by linuxgurugamer** [comment]
Yes, when the engine ignites, it gets armed, unless not possible (Oh, I see a small oversight, will need to add a check for enabled. It should only be enabled (local flag) if the part is researched and paid for.
The module only gets added to parts which are SRBs (using the MM patch).
isArmed is working the same (detects the engine out, etc).
good point about the isEnabled, I've added that as well.
Just committed those two changes

**Comment by jsolson** [comment]
Now it's filling the log with errors every time an engine activates.

What I'm going to do unless you'd rather do it, is take the good from both of these classes and get them both on the same page. We're using the flags differently and they don't behave the same. This is what I'm going to do:

isArmed has a menu item and comes from the base class. It is the user toggle for detection on/off. This is consistent with the rest of the mod.
isModuleEnabled will be the master switch for completely enabling/disabling the PartModule. Setting this to false will hide the module for the user. The is researched test will set this.

References to enabled and isEnabled will removed.

**Comment by linuxgurugamer** [comment]
go ahead

**Pull request closed without merging**
